version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci: github: "
    labels: []
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /docker-testing/arch
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker-testing/debian
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker-testing/fedora
    schedule:
      interval: daily
